import type { Metadata } from "next";
import "./globals.css";   
 // ✅ Global Bootstrap CSS
import BootstrapClient from "./BootstrapClient"; // ✅ Your new loader

export const metadata: Metadata = {
  title: "Apartment Almere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body>
        <BootstrapClient /> {/* ✅ Loads Bootstrap JS only once on client */}
        {children}
      </body>
    </html>
  );
}
